model_reasoning_effort = "high"

[features]
streamable_shell = true
web_search_request = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

# [mcp_servers.aws-documentation]
# command = "uvx"
# args = ["awslabs.aws-documentation-mcp-server@latest"]
# env = { FASTMCP_LOG_LEVEL = "ERROR", AWS_DOCUMENTATION_PARTITION = "aws" }

# [mcp_servers.aws-knowledge]
# command = "uvx"
# args = ["mcp-proxy", "--transport", "streamablehttp", "https://knowledge-mcp.global.api.aws"]

# [mcp_servers.aws-pricing]
# command = "uvx"
# args = ["awslabs.aws-pricing-mcp-server@latest"]
# env = { FASTMCP_LOG_LEVEL = "ERROR", AWS_PROFILE = "!!YOUR-AWS-PROFILE!!" }
