git:
  pagers:
    # | key to toggle between side-by-side and unified view
    - pager: delta --no-gitconfig --paging=never --side-by-side --line-numbers --syntax-theme=none
    - pager: delta --no-gitconfig --paging=never --line-numbers --syntax-theme=none
gui:
  # Nord Theme
  theme:
    activeBorderColor:
      - "#88C0D0"
      - bold
    inactiveBorderColor:
      - "#4C566A"
    searchingActiveBorderColor:
      - "#EBCB8B"
      - bold
    optionsTextColor:
      - "#D8DEE9"
    selectedLineBgColor:
      - "#3B4252"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#B48EAD"
    cherryPickedCommitBgColor:
      - "#3B4252"
    unstagedChangesColor:
      - "#BF616A"
    defaultFgColor:
      - "#ECEFF4"
