[finder]
preview = true

[naming]
template = '{{.Owner}}/{{.Repository}}={{.Branch}}'

[naming.sanitize_chars]
'/' = '-'
':' = '-'

[ui]
icons = true
tilde_home = true

[worktree]
auto_mkdir = true
basedir = '~/ghq/github.com'
